Controllers films users
evgeniy-schekoldin/java-filmorate pull request #2
Opened 2022-05-31 07:08 UTC by evgeniy-schekoldin

2022-05-31 22:49 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int id;
для генерации можно сделать отдельный класс `FilmIdGenerator`

2022-05-31 22:50 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
200 стоит вынести в константу

2022-05-31 22:53 UTC, makholin requested changes
Нужно исправить замечания

2022-06-01 06:45 UTC, evgeniy-schekoldin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > 200) {
+

2022-06-01 06:45 UTC, evgeniy-schekoldin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private int id;
+

2022-06-01 22:30 UTC, makholin commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotFoundException.java
> +@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
лучше использовать NOT_FOUND

2022-06-01 22:32 UTC, makholin approved these changes
Работа принята

2022-06-02 05:40 UTC, evgeniy-schekoldin commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotFoundException.java
> +@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
Тесты в Postman и Github почему-то ждут код ответа 500:

2022-06-02 05:40 UTC, evgeniy-schekoldin commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotFoundException.java
> +@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
pm.test("Status code is 500", function () {
    pm.response.to.have.status(500);
});

2022-06-14 05:52 UTC, merged